version: '3.8'

services:

  worker:
    build:
      context: .
      dockerfile: celeryWorker.Dockerfile
    command: celery --app worker.celery worker --loglevel=info --logfile=logs/celery.log
    depends_on:
      - redis
    networks:
      - opencheiron-public

  redis:
    image: redis:7
    ports:
          - "6379:6379"
    networks:
      - opencheiron-public

networks:
  opencheiron-public:
    name: opencheiron-public
    driver: bridge