version: '3.8'

services:

  worker:
    build:
      context: .
      dockerfile: celeryWorker.Dockerfile
    command: celery --app worker.celery worker --loglevel=info --logfile=logs/celery.log
    depends_on:
      - redis
      - postgres-management
    networks:
      - opencheiron-public

  redis:
    image: redis:7
    ports:
          - "6379:6379"
    networks:
      - opencheiron-public

  postgres-management:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - opencheiron-public

networks:
  opencheiron-public:
    name: opencheiron-public
    driver: bridge
